version: '3'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI} # This will use your MongoDB Atlas URL from Railway environment variables
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend/task-management-client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
